import type { Metadata } from "next";
import { Geist, Geist_Mono, Lexend_Deca, Raleway } from "next/font/google";
import "./globals.css";
import Footer from "./components/footer";
import Header from "./components/header";


const LexendSans = Lexend_Deca({
  variable: "--font-lexend",
  subsets: ["latin"]
})

const RalewaySans = Raleway({
  variable: "--font-raleway",
  subsets: ["latin"]
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Hello From Sabiyou",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
    shortcut: "/favicon.ico",
    apple: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${LexendSans.variable} ${RalewaySans.variable} antialiased`}
      >
        <Header />
        <main className="font-light container mx-auto">
        {children}
        </main>


        <Footer />
       

      </body>
    </html>
  );
}
